# **File Handling in Python**

File handling in Python means giving your program the ability to work with files on your computer just like how you use Notepad or Word to open, read, and write documents.

**Why is this important?**

As a data scientist, you'll constantly work with:

* CSV files containing datasets
* JSON files from APIs and web services
* Text files for logs and reports
* Saving your analysis results and model output


**Analogy**

File handling in Python is like working with a diary:

Open it to read or write (accessing a file)

Read what's there or write new notes (processing data)

Close it when you're done (releasing the file so other programs can use it)


**Opening and Closing Files**

The most basic way to work with files uses the **open()** function:

In [ ]:
# Opening a file

file = open('TS academy.txt', 'r')  # 'r' means read mode
content = file.read()          # Read the entire file
print(content)
file.close()                   # IMPORTANT: Always close!

This program is changing lifes.


| Mode | Meaning |
|---|---|
| "r" | Read – Opens a file for reading (file must exist) |
| "w" | Write – Creates a file or overwrites an existing one |
| "a" | Append – Opens file for writing at the end (keeps previous content) |

**1. "w" – Write (overwrites)**

In [ ]:
file = open("TS academy.txt", "w")
file.write("This program is changing lifes.")
file.close()


# Note

# If file doesn't exist, it creates it.

# If it exists, it deletes old content.

**2. "r" – Read a file**

In [ ]:
file = open("TS academy.txt", "r")
print(file.read())
file.close()

# If TS academy.txt doesn't exist, it will throw an error.

This program is changing lifes.
 This line is added at the end.
This line is added at the end.
We just added this line.


**3. "a" – Append (keep old, add new)**

In [ ]:
file = open("TS academy.txt", "a")
file.write("\nWe just added this line.")
file.close()

# Adds content without deleting what's already there.

## **The with Statement (Context Manager)**

**What is the with Statement?**

The with statement in Python is a context manager - a special way to handle resources that need to be set up and cleaned up properly.

Data scientists prefer the with statement because it automatically closes the file, even if an error occurs.

In [ ]:
# Open the door
file = open('TS academy.txt', 'r')

# Do your work
print(file.read())

# MUST remember to close the door!
file.close()

This program is changing lifes.


**With with (The Smart Way):**

In [ ]:
# Opens AND automatically closes when done
with open('TS academy.txt', 'r') as file:
    print(file.read())
# File is automatically closed here - even if errors occur!

This program is changing lifes.


# **What happens when you don't close files:**

* Memory leaks - wasted memory
* File locks - other programs can't access the file
* System limits - operating systems limit how many files you can open
* Corruption risk - data might not be fully written to disk

# **Introduction to NumPy Arrays**
**What is NumPy?**

NumPy (Numerical Python) is a powerful library for working with arrays and numerical computations. It's the backbone of almost every data science library in Python, including Pandas, Scikit-learn, and TensorFlow.


In [ ]:
numbers = [1, 2, 3, 4]
new_numbers = [] # create an empty list to store the results

for n in numbers: #goes through each number in numbers
    new_numbers.append(n + 5)

print(new_numbers)

[6, 7, 8, 9]


In [ ]:
# Fast and clean
import numpy as np

arr = np.array([1, 2, 3, 4]) # An array is a special container (like a list) that holds multiple values
print(arr + 5)

[6 7 8 9]


**Key Benefits of NumPy:**

* Speed: 50-100x faster than Python lists
* Memory Efficient: Uses less memory
* Vectorization: Perform operations on entire arrays at once
* Rich Functionality: Thousands of mathematical functions
* Foundation: Required for Pandas, Scikit-learn, TensorFlow

**Real-World Applications:**

* Analyzing millions of customer transactions
* Processing genomic data
* Financial modeling and risk analysis
* Image processing (images are arrays!)
* Machine learning algorithms

**Installing and Importing NumPy**

In [ ]:
# Install via pip (if not already installed)
# pip install numpy

In [ ]:
import numpy as np  # 'np' is the standard alias

**Always use np as the alias - it's the industry standard**

# **Creating NumPy Arrays**

**1D Array = One Dimension**

A single line of values, like a regular list.


In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]




**2D Array = Two Dimensions**

A table — has rows and columns (like a matrix).



In [ ]:
arr_2 = np.array([[1, 2, 3], [3, 4, 5]])
print(arr_2)

[[1 2 3]
 [3 4 5]]


**Array Attributes**

Every NumPy array has important attributes:

In [ ]:
print(arr_2.shape)     # Shape (length, or rows x columns)
print(arr_2.ndim)      # Number of dimensions (1D, 2D, etc.)
print(arr_2.dtype)     # Data type (int32, float64)

(2, 3)
2
int64


Basic Math with Arrays (Vectorized Operations)

**No loop needed**

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr + 10)
print(arr * 2)
print(arr ** 2)

[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]


**Reshaping Arrays**

Reshape 1D to 2D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


**Indexing and Slicing**

Same as lists but works on 2D too.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])

10
50
[20 30 40]


In [ ]:
matrix = np.array([
 [1, 2, 3],
 [4, 5, 6]])


print(matrix[0, 1])
print(matrix[1, 2])

2
6



**Matrix Operations**

Matrix addition and multiplication

In [ ]:
A = np.array([
 [1, 2],
 [3, 4]])

B = np.array([
    [5, 6],
    [7, 8]])

In [ ]:
print(A + B)         # Element-wise addition

print(A * B)         # Element-wise multiplication

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]



**Array Filtering**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2])

[3 4 5]


### Video Tutorials

* [Dave Gray - Python File Handling for Beginners](https://www.youtube.com/watch?v=BRrem1k3904)
* [NumPy Tutorial:  Your Entry to learning Data Science](https://www.youtube.com/playlist?list=PLhTjy8cBISEpTyVbZGYUesjpeUXth8rqs)


### Official Documentation
* [Python Documentation](https://docs.python.org/3/): The official Python documentation is an excellent resource for in-depth understanding of Python's features.
### Website
* [w3schools - Python](https://www.w3schools.com/python/)

*Note: Suggested resources are not affiliated or sponsoring this project.*

